export type VideoAnalysis = {
  durationMs: number;
  width: number;
  height: number;
  frameRate: number | null;
  audio: "present" | "absent" | "unknown";
  transcript: string;
  scenes: { atMs: number; summary: string }[];
};

export function videoGenerationStatus(env: { videoKey?: string } = {}): {
  status: "NOT_CONNECTED" | "CONFIGURED";
  provider: "xai:video";
  detail: string;
} {
  if (!env.videoKey?.trim()) {
    return {
      status: "NOT_CONNECTED",
      provider: "xai:video",
      detail: "The xAI video adapter is implemented. Set XAI_API_KEY before a job can be submitted. No clip was created.",
    };
  }
  return {
    status: "CONFIGURED",
    provider: "xai:video",
    detail: "XAI_API_KEY is set. A clip is stored only after the xAI job returns video bytes. Nothing has been generated by this status check.",
  };
}

/** Missing video analysis cannot approve. This does not invent a transcript. */
export function videoQa(analysis: VideoAnalysis | null): {
  decision: "HUMAN_REVIEW" | "REJECT";
  reason: string;
} {
  if (!analysis) {
    return { decision: "HUMAN_REVIEW", reason: "No video analysis is connected. The creative is not approved from a missing watch." };
  }
  if (analysis.durationMs <= 0 || analysis.width <= 0 || analysis.height <= 0) {
    return { decision: "REJECT", reason: "The video file has no usable duration or dimensions." };
  }
  if (!analysis.transcript.trim() && analysis.scenes.length === 0) {
    return { decision: "HUMAN_REVIEW", reason: "The video has timing metadata but no transcript or scene evidence." };
  }
  return { decision: "HUMAN_REVIEW", reason: "Video evidence is stored. It does not auto-approve publishing." };
}

/** Reads duration from an MP4 mvhd box. Missing boxes return null. No transcript is invented. */
export function readMp4Timing(bytes: Uint8Array): { durationMs: number; timescale: number } | null {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  return walk(view, 0, bytes.byteLength, 0);
}

function walk(view: DataView, start: number, end: number, depth: number): { durationMs: number; timescale: number } | null {
  if (depth > 6) return null;
  let offset = start;
  while (offset + 8 <= end) {
    let size = view.getUint32(offset);
    const type = String.fromCharCode(view.getUint8(offset + 4), view.getUint8(offset + 5), view.getUint8(offset + 6), view.getUint8(offset + 7));
    let header = 8;
    if (size === 1) {
      if (offset + 16 > end) return null;
      size = view.getUint32(offset + 12);
      header = 16;
    }
    if (size < header || offset + size > end) return null;
    if (type === "mvhd") return readMvhd(view, offset + header, offset + size);
    if (type === "moov" || type === "trak" || type === "mdia") {
      const nested = walk(view, offset + header, offset + size, depth + 1);
      if (nested) return nested;
    }
    offset += size;
  }
  return null;
}

function readMvhd(view: DataView, start: number, end: number): { durationMs: number; timescale: number } | null {
  if (start + 20 > end) return null;
  const version = view.getUint8(start);
  if (version === 0) {
    const timescale = view.getUint32(start + 12);
    const duration = view.getUint32(start + 16);
    if (timescale <= 0) return null;
    return { durationMs: Math.round((duration / timescale) * 1000), timescale };
  }
  if (version === 1 && start + 32 <= end) {
    const timescale = view.getUint32(start + 20);
    const duration = view.getUint32(start + 28);
    if (timescale <= 0) return null;
    return { durationMs: Math.round((duration / timescale) * 1000), timescale };
  }
  return null;
}
