export type IntegrationStatus = "CONNECTED" | "AVAILABLE" | "NOT_CONNECTED" | "FAILED" | "DISABLED";

/** Static contracts. Runtime keys are checked by the provider modules, not here. */
export const INTEGRATIONS = [
  {
    id: "ad_library",
    status: "NOT_CONNECTED" as const,
    detail: "Meta Ad Library client is implemented. It stays not connected until META_AD_LIBRARY_TOKEN is set and a request succeeds. No ads are collected before that.",
  },
  {
    id: "meta_publish",
    status: "NOT_CONNECTED" as const,
    detail: "Nothing is published to Meta.",
  },
  {
    id: "tiktok_publish",
    status: "NOT_CONNECTED" as const,
    detail: "Nothing is published to TikTok.",
  },
  {
    id: "neural_embedding",
    status: "AVAILABLE" as const,
    detail: "local:semantic (MiniLM) runs in process. An external embeddings API stays not connected until EXTERNAL_SEMANTIC_URL and EXTERNAL_SEMANTIC_KEY are set.",
  },
  {
    id: "lexical_similarity",
    status: "AVAILABLE" as const,
    detail: "Token hashing over stored text. It is not a semantic model.",
  },
  {
    id: "performance_feed",
    status: "NOT_CONNECTED" as const,
    detail: "Manual performance entry is available. Meta, TikTok, and Google insight sync stay not connected until a healthy account exists. No metrics are invented.",
  },
  {
    id: "video",
    status: "NOT_CONNECTED" as const,
    detail: "Hypit is the only production video engine. Configure HYPIT_BASE_URL; no clip was generated by this status check.",
  },
] as const satisfies readonly { id: string; status: IntegrationStatus; detail: string }[];
