/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as BrandsNewRouteImport } from './routes/brands/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BrandsBrandIdIndexRouteImport } from './routes/brands/$brandId/index'
import { Route as BrandsBrandIdBrainRouteImport } from './routes/brands/$brandId/brain'
import { Route as BrandsBrandIdIntelligenceRouteImport } from './routes/brands/$brandId/intelligence'
import { Route as BrandsBrandIdLearningRouteImport } from './routes/brands/$brandId/learning'
import { Route as BrandsBrandIdLibraryRouteImport } from './routes/brands/$brandId/library'
import { Route as BrandsBrandIdMarketRouteImport } from './routes/brands/$brandId/market'
import { Route as BrandsBrandIdOpportunitiesRouteImport } from './routes/brands/$brandId/opportunities'
import { Route as BrandsBrandIdProductsRouteImport } from './routes/brands/$brandId/products'
import { Route as BrandsBrandIdReviewsRouteImport } from './routes/brands/$brandId/reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNewRoute = BrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdIndexRoute = BrandsBrandIdIndexRouteImport.update({
  id: '/brands/$brandId/',
  path: '/brands/$brandId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdBrainRoute = BrandsBrandIdBrainRouteImport.update({
  id: '/brands/$brandId/brain',
  path: '/brands/$brandId/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdIntelligenceRoute =
  BrandsBrandIdIntelligenceRouteImport.update({
    id: '/brands/$brandId/intelligence',
    path: '/brands/$brandId/intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandsBrandIdLearningRoute = BrandsBrandIdLearningRouteImport.update({
  id: '/brands/$brandId/learning',
  path: '/brands/$brandId/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdLibraryRoute = BrandsBrandIdLibraryRouteImport.update({
  id: '/brands/$brandId/library',
  path: '/brands/$brandId/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdMarketRoute = BrandsBrandIdMarketRouteImport.update({
  id: '/brands/$brandId/market',
  path: '/brands/$brandId/market',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdOpportunitiesRoute =
  BrandsBrandIdOpportunitiesRouteImport.update({
    id: '/brands/$brandId/opportunities',
    path: '/brands/$brandId/opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandsBrandIdProductsRoute = BrandsBrandIdProductsRouteImport.update({
  id: '/brands/$brandId/products',
  path: '/brands/$brandId/products',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdReviewsRoute = BrandsBrandIdReviewsRouteImport.update({
  id: '/brands/$brandId/reviews',
  path: '/brands/$brandId/reviews',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/brands/new': typeof BrandsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/intelligence': typeof BrandsBrandIdIntelligenceRoute
  '/brands/$brandId/learning': typeof BrandsBrandIdLearningRoute
  '/brands/$brandId/library': typeof BrandsBrandIdLibraryRoute
  '/brands/$brandId/market': typeof BrandsBrandIdMarketRoute
  '/brands/$brandId/opportunities': typeof BrandsBrandIdOpportunitiesRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
  '/brands/$brandId/reviews': typeof BrandsBrandIdReviewsRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/brands/new': typeof BrandsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/intelligence': typeof BrandsBrandIdIntelligenceRoute
  '/brands/$brandId/learning': typeof BrandsBrandIdLearningRoute
  '/brands/$brandId/library': typeof BrandsBrandIdLibraryRoute
  '/brands/$brandId/market': typeof BrandsBrandIdMarketRoute
  '/brands/$brandId/opportunities': typeof BrandsBrandIdOpportunitiesRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
  '/brands/$brandId/reviews': typeof BrandsBrandIdReviewsRoute
  '/brands/$brandId': typeof BrandsBrandIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/brands/new': typeof BrandsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/intelligence': typeof BrandsBrandIdIntelligenceRoute
  '/brands/$brandId/learning': typeof BrandsBrandIdLearningRoute
  '/brands/$brandId/library': typeof BrandsBrandIdLibraryRoute
  '/brands/$brandId/market': typeof BrandsBrandIdMarketRoute
  '/brands/$brandId/opportunities': typeof BrandsBrandIdOpportunitiesRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
  '/brands/$brandId/reviews': typeof BrandsBrandIdReviewsRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integrations'
    | '/login'
    | '/settings'
    | '/api/health'
    | '/brands/new'
    | '/api/auth/$'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/intelligence'
    | '/brands/$brandId/learning'
    | '/brands/$brandId/library'
    | '/brands/$brandId/market'
    | '/brands/$brandId/opportunities'
    | '/brands/$brandId/products'
    | '/brands/$brandId/reviews'
    | '/brands/$brandId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integrations'
    | '/login'
    | '/settings'
    | '/api/health'
    | '/brands/new'
    | '/api/auth/$'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/intelligence'
    | '/brands/$brandId/learning'
    | '/brands/$brandId/library'
    | '/brands/$brandId/market'
    | '/brands/$brandId/opportunities'
    | '/brands/$brandId/products'
    | '/brands/$brandId/reviews'
    | '/brands/$brandId'
  id:
    | '__root__'
    | '/'
    | '/integrations'
    | '/login'
    | '/settings'
    | '/api/health'
    | '/brands/new'
    | '/api/auth/$'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/intelligence'
    | '/brands/$brandId/learning'
    | '/brands/$brandId/library'
    | '/brands/$brandId/market'
    | '/brands/$brandId/opportunities'
    | '/brands/$brandId/products'
    | '/brands/$brandId/reviews'
    | '/brands/$brandId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BrandsNewRoute: typeof BrandsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  BrandsBrandIdBrainRoute: typeof BrandsBrandIdBrainRoute
  BrandsBrandIdIntelligenceRoute: typeof BrandsBrandIdIntelligenceRoute
  BrandsBrandIdLearningRoute: typeof BrandsBrandIdLearningRoute
  BrandsBrandIdLibraryRoute: typeof BrandsBrandIdLibraryRoute
  BrandsBrandIdMarketRoute: typeof BrandsBrandIdMarketRoute
  BrandsBrandIdOpportunitiesRoute: typeof BrandsBrandIdOpportunitiesRoute
  BrandsBrandIdProductsRoute: typeof BrandsBrandIdProductsRoute
  BrandsBrandIdReviewsRoute: typeof BrandsBrandIdReviewsRoute
  BrandsBrandIdIndexRoute: typeof BrandsBrandIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/new': {
      id: '/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof BrandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/': {
      id: '/brands/$brandId/'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof BrandsBrandIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/brain': {
      id: '/brands/$brandId/brain'
      path: '/brands/$brandId/brain'
      fullPath: '/brands/$brandId/brain'
      preLoaderRoute: typeof BrandsBrandIdBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/intelligence': {
      id: '/brands/$brandId/intelligence'
      path: '/brands/$brandId/intelligence'
      fullPath: '/brands/$brandId/intelligence'
      preLoaderRoute: typeof BrandsBrandIdIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/learning': {
      id: '/brands/$brandId/learning'
      path: '/brands/$brandId/learning'
      fullPath: '/brands/$brandId/learning'
      preLoaderRoute: typeof BrandsBrandIdLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/library': {
      id: '/brands/$brandId/library'
      path: '/brands/$brandId/library'
      fullPath: '/brands/$brandId/library'
      preLoaderRoute: typeof BrandsBrandIdLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/market': {
      id: '/brands/$brandId/market'
      path: '/brands/$brandId/market'
      fullPath: '/brands/$brandId/market'
      preLoaderRoute: typeof BrandsBrandIdMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/opportunities': {
      id: '/brands/$brandId/opportunities'
      path: '/brands/$brandId/opportunities'
      fullPath: '/brands/$brandId/opportunities'
      preLoaderRoute: typeof BrandsBrandIdOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/products': {
      id: '/brands/$brandId/products'
      path: '/brands/$brandId/products'
      fullPath: '/brands/$brandId/products'
      preLoaderRoute: typeof BrandsBrandIdProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/reviews': {
      id: '/brands/$brandId/reviews'
      path: '/brands/$brandId/reviews'
      fullPath: '/brands/$brandId/reviews'
      preLoaderRoute: typeof BrandsBrandIdReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  BrandsNewRoute: BrandsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  BrandsBrandIdBrainRoute: BrandsBrandIdBrainRoute,
  BrandsBrandIdIntelligenceRoute: BrandsBrandIdIntelligenceRoute,
  BrandsBrandIdLearningRoute: BrandsBrandIdLearningRoute,
  BrandsBrandIdLibraryRoute: BrandsBrandIdLibraryRoute,
  BrandsBrandIdMarketRoute: BrandsBrandIdMarketRoute,
  BrandsBrandIdOpportunitiesRoute: BrandsBrandIdOpportunitiesRoute,
  BrandsBrandIdProductsRoute: BrandsBrandIdProductsRoute,
  BrandsBrandIdReviewsRoute: BrandsBrandIdReviewsRoute,
  BrandsBrandIdIndexRoute: BrandsBrandIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
