/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as Char91_designChar93RouteImport } from './routes/[_design]'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppExportsRouteImport } from './routes/_app/exports'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInviteRouteImport } from './routes/_app/invite'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppWebhooksRouteImport } from './routes/_app/webhooks'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppBrandsNewRouteImport } from './routes/_app/brands/new'
import { Route as ApiAssetsAssetIdRouteImport } from './routes/api/assets/$assetId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOauthCallbackRouteImport } from './routes/api/oauth/callback'
import { Route as ApiWebhooksReceiveRouteImport } from './routes/api/webhooks/receive'
import { Route as AppBrandsBrandIdIndexRouteImport } from './routes/_app/brands/$brandId/index'
import { Route as AppBrandsBrandIdAccountsRouteImport } from './routes/_app/brands/$brandId/accounts'
import { Route as AppBrandsBrandIdBrainRouteImport } from './routes/_app/brands/$brandId/brain'
import { Route as AppBrandsBrandIdCalibrationRouteImport } from './routes/_app/brands/$brandId/calibration'
import { Route as AppBrandsBrandIdFactoryRouteImport } from './routes/_app/brands/$brandId/factory'
import { Route as AppBrandsBrandIdIntelligenceRouteImport } from './routes/_app/brands/$brandId/intelligence'
import { Route as AppBrandsBrandIdLearningRouteImport } from './routes/_app/brands/$brandId/learning'
import { Route as AppBrandsBrandIdLibraryRouteImport } from './routes/_app/brands/$brandId/library'
import { Route as AppBrandsBrandIdMarketRouteImport } from './routes/_app/brands/$brandId/market'
import { Route as AppBrandsBrandIdOpportunitiesRouteImport } from './routes/_app/brands/$brandId/opportunities'
import { Route as AppBrandsBrandIdProductsRouteImport } from './routes/_app/brands/$brandId/products'
import { Route as AppBrandsBrandIdReviewsRouteImport } from './routes/_app/brands/$brandId/reviews'
import { Route as AppBrandsBrandIdStudioRouteImport } from './routes/_app/brands/$brandId/studio'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_designChar93Route = Char91_designChar93RouteImport.update({
  id: '/_design',
  path: '/_design',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrandsNewRoute = AppBrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAssetsAssetIdRoute = ApiAssetsAssetIdRouteImport.update({
  id: '/api/assets/$assetId',
  path: '/api/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCallbackRoute = ApiOauthCallbackRouteImport.update({
  id: '/api/oauth/callback',
  path: '/api/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksReceiveRoute = ApiWebhooksReceiveRouteImport.update({
  id: '/api/webhooks/receive',
  path: '/api/webhooks/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrandsBrandIdIndexRoute = AppBrandsBrandIdIndexRouteImport.update({
  id: '/brands/$brandId/',
  path: '/brands/$brandId/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsBrandIdAccountsRoute =
  AppBrandsBrandIdAccountsRouteImport.update({
    id: '/brands/$brandId/accounts',
    path: '/brands/$brandId/accounts',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrandsBrandIdBrainRoute = AppBrandsBrandIdBrainRouteImport.update({
  id: '/brands/$brandId/brain',
  path: '/brands/$brandId/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsBrandIdCalibrationRoute =
  AppBrandsBrandIdCalibrationRouteImport.update({
    id: '/brands/$brandId/calibration',
    path: '/brands/$brandId/calibration',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrandsBrandIdFactoryRoute = AppBrandsBrandIdFactoryRouteImport.update({
  id: '/brands/$brandId/factory',
  path: '/brands/$brandId/factory',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsBrandIdIntelligenceRoute =
  AppBrandsBrandIdIntelligenceRouteImport.update({
    id: '/brands/$brandId/intelligence',
    path: '/brands/$brandId/intelligence',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrandsBrandIdLearningRoute =
  AppBrandsBrandIdLearningRouteImport.update({
    id: '/brands/$brandId/learning',
    path: '/brands/$brandId/learning',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrandsBrandIdLibraryRoute = AppBrandsBrandIdLibraryRouteImport.update({
  id: '/brands/$brandId/library',
  path: '/brands/$brandId/library',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsBrandIdMarketRoute = AppBrandsBrandIdMarketRouteImport.update({
  id: '/brands/$brandId/market',
  path: '/brands/$brandId/market',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsBrandIdOpportunitiesRoute =
  AppBrandsBrandIdOpportunitiesRouteImport.update({
    id: '/brands/$brandId/opportunities',
    path: '/brands/$brandId/opportunities',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrandsBrandIdProductsRoute =
  AppBrandsBrandIdProductsRouteImport.update({
    id: '/brands/$brandId/products',
    path: '/brands/$brandId/products',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrandsBrandIdReviewsRoute = AppBrandsBrandIdReviewsRouteImport.update({
  id: '/brands/$brandId/reviews',
  path: '/brands/$brandId/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsBrandIdStudioRoute = AppBrandsBrandIdStudioRouteImport.update({
  id: '/brands/$brandId/studio',
  path: '/brands/$brandId/studio',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/_design': typeof Char91_designChar93Route
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/exports': typeof AppExportsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/invite': typeof AppInviteRoute
  '/jobs': typeof AppJobsRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/webhooks': typeof AppWebhooksRoute
  '/api/health': typeof ApiHealthRoute
  '/brands/new': typeof AppBrandsNewRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/webhooks/receive': typeof ApiWebhooksReceiveRoute
  '/brands/$brandId/accounts': typeof AppBrandsBrandIdAccountsRoute
  '/brands/$brandId/brain': typeof AppBrandsBrandIdBrainRoute
  '/brands/$brandId/calibration': typeof AppBrandsBrandIdCalibrationRoute
  '/brands/$brandId/factory': typeof AppBrandsBrandIdFactoryRoute
  '/brands/$brandId/intelligence': typeof AppBrandsBrandIdIntelligenceRoute
  '/brands/$brandId/learning': typeof AppBrandsBrandIdLearningRoute
  '/brands/$brandId/library': typeof AppBrandsBrandIdLibraryRoute
  '/brands/$brandId/market': typeof AppBrandsBrandIdMarketRoute
  '/brands/$brandId/opportunities': typeof AppBrandsBrandIdOpportunitiesRoute
  '/brands/$brandId/products': typeof AppBrandsBrandIdProductsRoute
  '/brands/$brandId/reviews': typeof AppBrandsBrandIdReviewsRoute
  '/brands/$brandId/studio': typeof AppBrandsBrandIdStudioRoute
  '/brands/$brandId/': typeof AppBrandsBrandIdIndexRoute
}
export interface FileRoutesByTo {
  '/_design': typeof Char91_designChar93Route
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/exports': typeof AppExportsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/invite': typeof AppInviteRoute
  '/jobs': typeof AppJobsRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/webhooks': typeof AppWebhooksRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AppIndexRoute
  '/brands/new': typeof AppBrandsNewRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/webhooks/receive': typeof ApiWebhooksReceiveRoute
  '/brands/$brandId/accounts': typeof AppBrandsBrandIdAccountsRoute
  '/brands/$brandId/brain': typeof AppBrandsBrandIdBrainRoute
  '/brands/$brandId/calibration': typeof AppBrandsBrandIdCalibrationRoute
  '/brands/$brandId/factory': typeof AppBrandsBrandIdFactoryRoute
  '/brands/$brandId/intelligence': typeof AppBrandsBrandIdIntelligenceRoute
  '/brands/$brandId/learning': typeof AppBrandsBrandIdLearningRoute
  '/brands/$brandId/library': typeof AppBrandsBrandIdLibraryRoute
  '/brands/$brandId/market': typeof AppBrandsBrandIdMarketRoute
  '/brands/$brandId/opportunities': typeof AppBrandsBrandIdOpportunitiesRoute
  '/brands/$brandId/products': typeof AppBrandsBrandIdProductsRoute
  '/brands/$brandId/reviews': typeof AppBrandsBrandIdReviewsRoute
  '/brands/$brandId/studio': typeof AppBrandsBrandIdStudioRoute
  '/brands/$brandId': typeof AppBrandsBrandIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_design': typeof Char91_designChar93Route
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/invite': typeof AppInviteRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/brands/new': typeof AppBrandsNewRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/webhooks/receive': typeof ApiWebhooksReceiveRoute
  '/_app/brands/$brandId/accounts': typeof AppBrandsBrandIdAccountsRoute
  '/_app/brands/$brandId/brain': typeof AppBrandsBrandIdBrainRoute
  '/_app/brands/$brandId/calibration': typeof AppBrandsBrandIdCalibrationRoute
  '/_app/brands/$brandId/factory': typeof AppBrandsBrandIdFactoryRoute
  '/_app/brands/$brandId/intelligence': typeof AppBrandsBrandIdIntelligenceRoute
  '/_app/brands/$brandId/learning': typeof AppBrandsBrandIdLearningRoute
  '/_app/brands/$brandId/library': typeof AppBrandsBrandIdLibraryRoute
  '/_app/brands/$brandId/market': typeof AppBrandsBrandIdMarketRoute
  '/_app/brands/$brandId/opportunities': typeof AppBrandsBrandIdOpportunitiesRoute
  '/_app/brands/$brandId/products': typeof AppBrandsBrandIdProductsRoute
  '/_app/brands/$brandId/reviews': typeof AppBrandsBrandIdReviewsRoute
  '/_app/brands/$brandId/studio': typeof AppBrandsBrandIdStudioRoute
  '/_app/brands/$brandId/': typeof AppBrandsBrandIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_design'
    | '/login'
    | '/$'
    | '/alerts'
    | '/audit'
    | '/exports'
    | '/integrations'
    | '/invite'
    | '/jobs'
    | '/notifications'
    | '/settings'
    | '/usage'
    | '/webhooks'
    | '/api/health'
    | '/brands/new'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/api/webhooks/receive'
    | '/brands/$brandId/accounts'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/calibration'
    | '/brands/$brandId/factory'
    | '/brands/$brandId/intelligence'
    | '/brands/$brandId/learning'
    | '/brands/$brandId/library'
    | '/brands/$brandId/market'
    | '/brands/$brandId/opportunities'
    | '/brands/$brandId/products'
    | '/brands/$brandId/reviews'
    | '/brands/$brandId/studio'
    | '/brands/$brandId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/_design'
    | '/login'
    | '/$'
    | '/alerts'
    | '/audit'
    | '/exports'
    | '/integrations'
    | '/invite'
    | '/jobs'
    | '/notifications'
    | '/settings'
    | '/usage'
    | '/webhooks'
    | '/api/health'
    | '/'
    | '/brands/new'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/api/webhooks/receive'
    | '/brands/$brandId/accounts'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/calibration'
    | '/brands/$brandId/factory'
    | '/brands/$brandId/intelligence'
    | '/brands/$brandId/learning'
    | '/brands/$brandId/library'
    | '/brands/$brandId/market'
    | '/brands/$brandId/opportunities'
    | '/brands/$brandId/products'
    | '/brands/$brandId/reviews'
    | '/brands/$brandId/studio'
    | '/brands/$brandId'
  id:
    | '__root__'
    | '/_app'
    | '/_design'
    | '/login'
    | '/_app/$'
    | '/_app/alerts'
    | '/_app/audit'
    | '/_app/exports'
    | '/_app/integrations'
    | '/_app/invite'
    | '/_app/jobs'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/usage'
    | '/_app/webhooks'
    | '/api/health'
    | '/_app/'
    | '/_app/brands/new'
    | '/api/assets/$assetId'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/api/webhooks/receive'
    | '/_app/brands/$brandId/accounts'
    | '/_app/brands/$brandId/brain'
    | '/_app/brands/$brandId/calibration'
    | '/_app/brands/$brandId/factory'
    | '/_app/brands/$brandId/intelligence'
    | '/_app/brands/$brandId/learning'
    | '/_app/brands/$brandId/library'
    | '/_app/brands/$brandId/market'
    | '/_app/brands/$brandId/opportunities'
    | '/_app/brands/$brandId/products'
    | '/_app/brands/$brandId/reviews'
    | '/_app/brands/$brandId/studio'
    | '/_app/brands/$brandId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  Char91_designChar93Route: typeof Char91_designChar93Route
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAssetsAssetIdRoute: typeof ApiAssetsAssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOauthCallbackRoute: typeof ApiOauthCallbackRoute
  ApiWebhooksReceiveRoute: typeof ApiWebhooksReceiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_design': {
      id: '/_design'
      path: '/_design'
      fullPath: '/_design'
      preLoaderRoute: typeof Char91_designChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite': {
      id: '/_app/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/brands/new': {
      id: '/_app/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof AppBrandsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/assets/$assetId': {
      id: '/api/assets/$assetId'
      path: '/api/assets/$assetId'
      fullPath: '/api/assets/$assetId'
      preLoaderRoute: typeof ApiAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/callback': {
      id: '/api/oauth/callback'
      path: '/api/oauth/callback'
      fullPath: '/api/oauth/callback'
      preLoaderRoute: typeof ApiOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/receive': {
      id: '/api/webhooks/receive'
      path: '/api/webhooks/receive'
      fullPath: '/api/webhooks/receive'
      preLoaderRoute: typeof ApiWebhooksReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/brands/$brandId/': {
      id: '/_app/brands/$brandId/'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof AppBrandsBrandIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/accounts': {
      id: '/_app/brands/$brandId/accounts'
      path: '/brands/$brandId/accounts'
      fullPath: '/brands/$brandId/accounts'
      preLoaderRoute: typeof AppBrandsBrandIdAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/brain': {
      id: '/_app/brands/$brandId/brain'
      path: '/brands/$brandId/brain'
      fullPath: '/brands/$brandId/brain'
      preLoaderRoute: typeof AppBrandsBrandIdBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/calibration': {
      id: '/_app/brands/$brandId/calibration'
      path: '/brands/$brandId/calibration'
      fullPath: '/brands/$brandId/calibration'
      preLoaderRoute: typeof AppBrandsBrandIdCalibrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/factory': {
      id: '/_app/brands/$brandId/factory'
      path: '/brands/$brandId/factory'
      fullPath: '/brands/$brandId/factory'
      preLoaderRoute: typeof AppBrandsBrandIdFactoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/intelligence': {
      id: '/_app/brands/$brandId/intelligence'
      path: '/brands/$brandId/intelligence'
      fullPath: '/brands/$brandId/intelligence'
      preLoaderRoute: typeof AppBrandsBrandIdIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/learning': {
      id: '/_app/brands/$brandId/learning'
      path: '/brands/$brandId/learning'
      fullPath: '/brands/$brandId/learning'
      preLoaderRoute: typeof AppBrandsBrandIdLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/library': {
      id: '/_app/brands/$brandId/library'
      path: '/brands/$brandId/library'
      fullPath: '/brands/$brandId/library'
      preLoaderRoute: typeof AppBrandsBrandIdLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/market': {
      id: '/_app/brands/$brandId/market'
      path: '/brands/$brandId/market'
      fullPath: '/brands/$brandId/market'
      preLoaderRoute: typeof AppBrandsBrandIdMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/opportunities': {
      id: '/_app/brands/$brandId/opportunities'
      path: '/brands/$brandId/opportunities'
      fullPath: '/brands/$brandId/opportunities'
      preLoaderRoute: typeof AppBrandsBrandIdOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/products': {
      id: '/_app/brands/$brandId/products'
      path: '/brands/$brandId/products'
      fullPath: '/brands/$brandId/products'
      preLoaderRoute: typeof AppBrandsBrandIdProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/reviews': {
      id: '/_app/brands/$brandId/reviews'
      path: '/brands/$brandId/reviews'
      fullPath: '/brands/$brandId/reviews'
      preLoaderRoute: typeof AppBrandsBrandIdReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId/studio': {
      id: '/_app/brands/$brandId/studio'
      path: '/brands/$brandId/studio'
      fullPath: '/brands/$brandId/studio'
      preLoaderRoute: typeof AppBrandsBrandIdStudioRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppExportsRoute: typeof AppExportsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInviteRoute: typeof AppInviteRoute
  AppJobsRoute: typeof AppJobsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBrandsNewRoute: typeof AppBrandsNewRoute
  AppBrandsBrandIdAccountsRoute: typeof AppBrandsBrandIdAccountsRoute
  AppBrandsBrandIdBrainRoute: typeof AppBrandsBrandIdBrainRoute
  AppBrandsBrandIdCalibrationRoute: typeof AppBrandsBrandIdCalibrationRoute
  AppBrandsBrandIdFactoryRoute: typeof AppBrandsBrandIdFactoryRoute
  AppBrandsBrandIdIntelligenceRoute: typeof AppBrandsBrandIdIntelligenceRoute
  AppBrandsBrandIdLearningRoute: typeof AppBrandsBrandIdLearningRoute
  AppBrandsBrandIdLibraryRoute: typeof AppBrandsBrandIdLibraryRoute
  AppBrandsBrandIdMarketRoute: typeof AppBrandsBrandIdMarketRoute
  AppBrandsBrandIdOpportunitiesRoute: typeof AppBrandsBrandIdOpportunitiesRoute
  AppBrandsBrandIdProductsRoute: typeof AppBrandsBrandIdProductsRoute
  AppBrandsBrandIdReviewsRoute: typeof AppBrandsBrandIdReviewsRoute
  AppBrandsBrandIdStudioRoute: typeof AppBrandsBrandIdStudioRoute
  AppBrandsBrandIdIndexRoute: typeof AppBrandsBrandIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAuditRoute: AppAuditRoute,
  AppExportsRoute: AppExportsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInviteRoute: AppInviteRoute,
  AppJobsRoute: AppJobsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
  AppBrandsNewRoute: AppBrandsNewRoute,
  AppBrandsBrandIdAccountsRoute: AppBrandsBrandIdAccountsRoute,
  AppBrandsBrandIdBrainRoute: AppBrandsBrandIdBrainRoute,
  AppBrandsBrandIdCalibrationRoute: AppBrandsBrandIdCalibrationRoute,
  AppBrandsBrandIdFactoryRoute: AppBrandsBrandIdFactoryRoute,
  AppBrandsBrandIdIntelligenceRoute: AppBrandsBrandIdIntelligenceRoute,
  AppBrandsBrandIdLearningRoute: AppBrandsBrandIdLearningRoute,
  AppBrandsBrandIdLibraryRoute: AppBrandsBrandIdLibraryRoute,
  AppBrandsBrandIdMarketRoute: AppBrandsBrandIdMarketRoute,
  AppBrandsBrandIdOpportunitiesRoute: AppBrandsBrandIdOpportunitiesRoute,
  AppBrandsBrandIdProductsRoute: AppBrandsBrandIdProductsRoute,
  AppBrandsBrandIdReviewsRoute: AppBrandsBrandIdReviewsRoute,
  AppBrandsBrandIdStudioRoute: AppBrandsBrandIdStudioRoute,
  AppBrandsBrandIdIndexRoute: AppBrandsBrandIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  Char91_designChar93Route: Char91_designChar93Route,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAssetsAssetIdRoute: ApiAssetsAssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOauthCallbackRoute: ApiOauthCallbackRoute,
  ApiWebhooksReceiveRoute: ApiWebhooksReceiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
