/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BrandsNewRouteImport } from './routes/brands/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BrandsBrandIdIndexRouteImport } from './routes/brands/$brandId/index'
import { Route as BrandsBrandIdBrainRouteImport } from './routes/brands/$brandId/brain'
import { Route as BrandsBrandIdProductsRouteImport } from './routes/brands/$brandId/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNewRoute = BrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdIndexRoute = BrandsBrandIdIndexRouteImport.update({
  id: '/brands/$brandId/',
  path: '/brands/$brandId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdBrainRoute = BrandsBrandIdBrainRouteImport.update({
  id: '/brands/$brandId/brain',
  path: '/brands/$brandId/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdProductsRoute = BrandsBrandIdProductsRouteImport.update({
  id: '/brands/$brandId/products',
  path: '/brands/$brandId/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/brands/new': typeof BrandsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/brands/new': typeof BrandsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
  '/brands/$brandId': typeof BrandsBrandIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/brands/new': typeof BrandsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/brands/$brandId/brain': typeof BrandsBrandIdBrainRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/brands/new'
    | '/api/auth/$'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/products'
    | '/brands/$brandId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/brands/new'
    | '/api/auth/$'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/products'
    | '/brands/$brandId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/brands/new'
    | '/api/auth/$'
    | '/brands/$brandId/brain'
    | '/brands/$brandId/products'
    | '/brands/$brandId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  BrandsNewRoute: typeof BrandsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  BrandsBrandIdBrainRoute: typeof BrandsBrandIdBrainRoute
  BrandsBrandIdProductsRoute: typeof BrandsBrandIdProductsRoute
  BrandsBrandIdIndexRoute: typeof BrandsBrandIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/new': {
      id: '/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof BrandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/': {
      id: '/brands/$brandId/'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof BrandsBrandIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/brain': {
      id: '/brands/$brandId/brain'
      path: '/brands/$brandId/brain'
      fullPath: '/brands/$brandId/brain'
      preLoaderRoute: typeof BrandsBrandIdBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId/products': {
      id: '/brands/$brandId/products'
      path: '/brands/$brandId/products'
      fullPath: '/brands/$brandId/products'
      preLoaderRoute: typeof BrandsBrandIdProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  BrandsNewRoute: BrandsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  BrandsBrandIdBrainRoute: BrandsBrandIdBrainRoute,
  BrandsBrandIdProductsRoute: BrandsBrandIdProductsRoute,
  BrandsBrandIdIndexRoute: BrandsBrandIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
